name: Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: chee2e/testweb
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker build -t chee2e/testweb:${{ github.sha }} .
        
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml

#       - name: Run Trivy vulnerability scanner
#         uses: aquasecurity/trivy-action@master
#         with:
#           image-ref: 'chee2e/testweb:${{ github.sha }}'
#           format: 'json'
#           output: 'trivy-results.json'
#           exit-code: '0'
#           ignore-unfixed: true
      
      - name: Push trivy results to GitHub repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          repository: chee2e/trivy-test
          branch: main
          directory: .
          
#       - name: Upload Trivy results to Github repository
#         uses: actions/upload-artifact@v2
#         with:
#           name: results
#           path: results.json
          
#       - name: Push Trivy results to repository
#         run: |
#           git config --global user.email "pinkc47@naver.com"
#           git config --global user.name "chee2e"
#           git checkout ${{ github.ref }}
#           git add results.json
#           git commit -m "Add Trivy scan results"
#           git push
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
